### ISSUE TITLE
npm scripts vs Cordova hooks -- for build stage

### ISSUE THREAD

**Issue by devgeeks** [JedWatson/picture-tour-app#1]
Working on splitting a PhoneGap / Cordova template out from the app and couldn't remember our conversation about using npm scripts vs using Cordova hooks.

Do you remember why you went that way in the end?

**Comment by JedWatson** [comment]
There was a pretty strong sentiment that said "don't use hooks" from a couple of people at the conference - also the npm scripts are pretty simple, and consistent (e.g using `npm start` to run in dev mode w/o using cordova at all)

Is there any argument **for** using cordova hooks? Happy to change if it's a better user experience.

**Comment by devgeeks** [comment]
I think just in terms of a template (as opposed to an example app), hooks mean users just use the commands they know like `cordova build ios`, etc. Instead of having to learn commands specific to the template.

Having said that, we did come across some issues with running a long-running process like the hot reloading server.

_sigh_

Let me play with it and see what I can come up with.

My plan is to work on the template initially as a branch to this app, then split it off. I assume you don't want to maintain it, but it's important for the git history to remain and have your authorship be clear.

**Comment by devgeeks** [comment]
I left it as is. No hooks.
